replicaCount: 2

copies: 1

create_default: false
is_remote: true
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}


service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  
#NOTE: ADD THIS SECTION FROM THE base-values-<app>-<ns>.yaml
smartscaler:
  enabled: false
  deploymentName: "nginx"

volumes: []

volumeMounts: []


nodeSelector: {}

tolerations:
- operator: "Exists"

affinity: {}
