apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
spec:
  project: smartscaler-tutorials
  destination:
    server: "app-cluster"
    namespace: "app2"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
  sources:
    - repoURL: https://github.com/smart-scaler/smartscaler-agents-argocd-examples.git
      targetRevision: HEAD
      path: "charts/app2/"
      helm:
        # Release name override (defaults to application name)
        releaseName: "app2"
        valueFiles:
        - "../../charts/app2/values.yaml"
        - "../../charts/app2/values-override.yaml"
