apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
spec:
  project: smartscaler-tutorials
  destination:
    server: "app-cluster"
    namespace: "istio"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 2
  sources:
    - repoURL: https://github.com/smart-scaler/smartscaler-agents-argocd-examples.git
      targetRevision: HEAD
      path: "charts/istio/"
      helm:
        # Release name override (defaults to application name)
        releaseName: "istio"
