apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smartscaler-events
spec:
  project: smartscaler-tutorials
  destination:
    server: "app-cluster"
    namespace: smart-scaler
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
  sources:
    - repoURL: https://github.com/smart-scaler/smartscaler-agents-argocd-examples.git
      targetRevision: HEAD
      path: "charts/smartscaler-events/"
