apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smartscaler-agent
spec:
  project: smartscaler-tutorials
  destination:
    server: "app-cluster"
    namespace: smart-scaler
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
  sources:
    - repoURL: https://github.com/smart-scaler/smartscaler-agents-argocd-examples.git
      targetRevision: HEAD
      path: "charts/smartscaler-agent/"
      helm:
        # Release name override (defaults to application name)
        releaseName: "smartscaler-agent"
        valueFiles:
        - "../../charts/smartscaler-agent/global-values.yaml"
        - "../../charts/smartscaler-agent/inference-config-override.yaml"
