#NOTE: THIS FILE IS DOWNLOADED FROM https://ui.saas.smart-scaler.io/
agentConfiguration:
  host: https://gateway.saas.smart-scaler.io
  clusterDisplayName: tutorial-agent
  clientID: <client id value>
  # Do not change this
  clientSecret: <client secret value>
# The next 4 values will be emailed to you from Smart Scaler support.
# PLEASE WAIT TILL YOU RECEIVE THIS EMAIL BEFORE YOU PROCEED WITH THE INSTALLATION
smartscalerApi:
  password: "" #<apigateway-password-from-avesha-support-email>
  username: "" #<apigateway-username-from-avesha-support-email>
smartscalerMetrics:
  password: "" #<mertricgateway-password-from-avesha-support-email>
  username: "" #<mertricgateway-username-from-avesha-support-email>
# Enter the information for the relevant metrics data source. We currently support Datadog and # Prometheus. Support for more metrics sources is coming soon, please contact Smart Scaler support
# Depending on the available datasource, update the below section 
dataSources:
  datadog:
    existingSecret: "" ## if existingSecret value is provided then below values will be ignored, use below keys in existing secret
    apiKey: "" #<your-datadog-api-key>
    appkey: "" #<your-datadog-api-key>
  prometheus:
    existingSecret: "" ## if existingSecret value is provided then below values will be ignored, use below keys in existing secret
    username: "" #<your-prometheus-username>
    password: "" #<your-prometheus-password>
# Provide the API url for the relevant metrics data source.
inferenceAgent:
  inferenceAgentConfig:
    app_datasource:
      # Depending on the available datasource, update the below section
      prometheus:
        url: "" #<your-prometheus-url>
      datadog:
        url: "" #<your-datadog-url>

# NOTE: SET configHelper.enabled: true
configHelper:
  enabled: true
