# NOTE: DOWNLOAD THIS FILE FROM CONFIG-HELPER TOOL
# ADD THESE 2 SECTIONS IN THE APPLICATION IN KEDA NAMESPACE
apiVersion: v1
kind: Secret
metadata:
  name: keda-prom-secret
  namespace: keda
data:
  #NOTE: ENTER THE VAULT PATH FOR SMARTSCALERMETRICS
  username: # add the username for metricsgateway
  password: # add the password for metricdgateway
---
apiVersion: keda.sh/v1alpha1
kind: ClusterTriggerAuthentication
metadata:
  name: keda-prom-creds
  namespace: keda
spec:
  secretTargetRef:
    - parameter: username
      name: keda-prom-secret
      key: username
    - parameter: password
      name: keda-prom-secret
      key: password
