# Add these 2 sections in the keda application template
apiVersion: v1
kind: Secret
metadata:
  name: keda-prom-secret
  namespace: keda
data:
  #NOTE: ENTER THE VAULT PATH FOR SMARTSCALERMETRICS
  username: # add the username for metricsgateway
  password: # add the password for metricdgateway
---
apiVersion: keda.sh/v1alpha1
kind: ClusterTriggerAuthentication
metadata:
  name: keda-prom-creds
  namespace: keda
spec:
  secretTargetRef:
    - parameter: username
      name: keda-prom-secret
      key: username
    - parameter: password
      name: keda-prom-secret
      key: password
